### ISSUE TITLE
remove this from the internet

### ISSUE THREAD

**Issue by GregWoods** [rust-embedded/debugonomicon#22]
As a rust newbie I am frustrated by the amount of info which is outdated. I've wasted days following along tutorials which are poorly tested, and do not work with the latest tools and version of rust.
This project doesn't even appear to be that good. There is zero content, appears to be abandoned, and is just another waste of 5 minutes of everyone's time.
Sorry to be harsh

**Comment by therealprof** [comment]
This is not the right book to get started as Rust newbie. You might want to check out https://rust-embedded.github.io/book/ instead.

The debugonomicon is not abandoned and should work just fine, but of course if you're having troubles we're quite keen on hearing details about it so we can fix it.
